name: Push Application on Update
on:
    push:
        branches:
            - dev
        paths:
            - infrastructure_aws/**
jobs:
    sync:
        sync: Copy
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Check Out Code
              uses: actions/checkout@v4
            - name: Configure AWS Credentials
              id: aws-credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ env.aws-terraform-role }}
                  aws-region: us-west-2
                  output-credentials: true
            - name: Push Files to S3
              run: |
                export BUCKET_NAME=$(aws s3api list-buckets --output text --query "Buckets[?contains(Name,'example-')] | [0].Name")
                aws s3 sync . s3://$BUCKET_NAME
